# Generated by Django 4.2.4 on 2023-08-30 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='book id')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('category', models.CharField(max_length=70)),
                ('file', models.FileField(upload_to='files/%h')),
                ('description', models.TextField(blank=True)),
                ('publisher', models.CharField(max_length=150)),
                ('published', models.DateField(blank=True, null=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=3.99, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Subscription')),
            ],
        ),
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AV', 'Available'), ('NOTAV', 'Not Available'), ('CS', 'Comming Soon')], default='AV', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.book')),
            ],
        ),
    ]
