# Generated by Django 4.2.4 on 2023-08-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
